apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ggoods-hasura
  name: ggoods-hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ggoods-hasura
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ggoods-hasura
    spec:
      imagePullSecrets:
          - name: regcred
      containers:
        - args:
            - graphql-engine
            - serve
            - --enable-console
          envFrom:
            - configMapRef:
                name: ggoods-hasura-config
          image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
          imagePullPolicy: "IfNotPresent"
          name: "ggoods-hasura"
          ports:
            - containerPort: 8080
      restartPolicy: Always
